"use client"
import Head from "next/head";
//import ManualHeader from "../components/ManualHeader";
import Header from "../components/Header";
import LotteryEntrance from "@/components/LotteryEntrance";
import { useMoralis } from "react-moralis";

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div>
      <Head>
        <title>Smart Contract Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <LotteryEntrance/>
    </div>
  )
}
